name: governance

# on:
#   push:
#     branches: [main]
#     paths:
#       - governance/**
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

jobs:
  what-if:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run what-if deployment
        run: az deployment mg create --whatif --template-file governance/main.bicep
