name: management

on:
  push:
    branches: [main]
    paths:
      - platform/management/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  what-if:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run what-if deployment
        run: az deployment subscription create --whatif --template-file platform/management/main.bicep
